project_id = "otiwblujhejhazyiezbo"

[functions.generate-fitness-plan]
verify_jwt = false

[functions.generate-exercise-image]
verify_jwt = false

[functions.generate-motivation-quote]
verify_jwt = false